[package]
edition = "2024"
name = "example"
publish = false
version = "0.1.0"

[[bench]]
harness = false
name = "main"

[dependencies]
haste = { path = "..", features = ["tokio"] }
tokio = { version = "1.46.1", features = ["full"] }
